spring.application.name=Les-13-opdracht

# Define variables
POSTGRESQL_DATABASENAME = les13-opdracht
POSTGRESQL_USERNAME = postgres
POSTGRESQL_PASSWORD = password

# Define database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

#Define JPA settings, enable logging yes or no
spring.jpa.show-sql=true

#Force to generate data schema on startup of application
spring.jpa.generate-ddl=true
# create the tables, alternative is update on startup
spring.jpa.hibernate.ddl-auto=create

#database init with a data.sql file after hibernate
spring.sql.init.mode=always
#Whether to defer DataSource initialization until after any EntityManagerFactory beans have been created and initialized.
spring.jpa.defer-datasource-initialization=true
#Additional native properties to set on the JPA provider.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect





